namespace DrawingApp
{
    partial class Form1
    {
        /// <summary>
        /// Обов'язкова змінна конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Очистка використовуваних ресурсів.
        /// </summary>
        /// <param name="disposing">true, якщо керуючі ресурси повинні бути видалені; в іншому випадку false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by Windows Form Designer

        /// <summary>
        /// Метод, необхідний для підтримки конструктора - не змінюйте
        /// зміст цього методу за допомогою редактора коду.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.btnAddObject = new System.Windows.Forms.Button();
            this.btnDraw = new System.Windows.Forms.Button();
            this.btnMove = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // pictureBox1
            // 
            this.pictureBox1.Location = new System.Drawing.Point(12, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(400, 400);
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // btnAddObject
            // 
            this.btnAddObject.Location = new System.Drawing.Point(443, 38);
            this.btnAddObject.Name = "btnAddObject";
            this.btnAddObject.Size = new System.Drawing.Size(129, 35);
            this.btnAddObject.TabIndex = 1;
            this.btnAddObject.Text = "Додати об'єкт";
            this.btnAddObject.UseVisualStyleBackColor = true;
            this.btnAddObject.Click += new System.EventHandler(this.btnAddObject_Click);
            // 
            // btnDraw
            // 
            this.btnDraw.Location = new System.Drawing.Point(443, 106);
            this.btnDraw.Name = "btnDraw";
            this.btnDraw.Size = new System.Drawing.Size(129, 35);
            this.btnDraw.TabIndex = 2;
            this.btnDraw.Text = "Намалювати";
            this.btnDraw.UseVisualStyleBackColor = true;
            this.btnDraw.Click += new System.EventHandler(this.btnDraw_Click);
            // 
            // btnMove
            // 
            this.btnMove.Location = new System.Drawing.Point(443, 178);
            this.btnMove.Name = "btnMove";
            this.btnMove.Size = new System.Drawing.Size(129, 35);
            this.btnMove.TabIndex = 3;
            this.btnMove.Text = "Перемістити";
            this.btnMove.UseVisualStyleBackColor = true;
            this.btnMove.Click += new System.EventHandler(this.btnMove_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(584, 442);
            this.Controls.Add(this.btnMove);
            this.Controls.Add(this.btnDraw);
            this.Controls.Add(this.btnAddObject);
            this.Controls.Add(this.pictureBox1);
            this.Name = "Form1";
            this.Text = "Малюнок";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Button btnAddObject;
        private System.Windows.Forms.Button btnDraw;
        private System.Windows.Forms.Button btnMove;
    }
}
